on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  ics-scan-and-upload:
    name: insightCloudSec scan and upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan cloudformation template
        uses: rapid7/insightcloudsec-actions@latest
        with:
          api_key: ${{ secrets.ics_api_key }}
          base_url: ${{ secrets.ics_base_url }}
          config_name: AWS CIS Benchmark 1.4
          scan_name: Scan on Push
          target: example.yml
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: scan_output.sarif
